In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import seaborn as sns
import matplotlib.pyplot as plt
BASE = Path("../data/raw")

# Show all columns and wide output
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1200)
pd.set_option("display.max_colwidth", 100)

# Suppress mixed-type warnings from messy raw data
import warnings
warnings.filterwarnings("ignore")

In [2]:
crosswalk = pd.read_csv(BASE / "crossWalk.csv", encoding="latin1")
avonet_crosswalk = pd.read_csv(BASE / "Avonet/avonet_crosswalk.csv")
avonet = pd.read_csv(BASE / "Avonet/avonet_uncleaned_final_dataset.csv")
birdbase = pd.read_csv(BASE / "Birdbase/birdbase_uncleaned_final_dataset.csv")
# birdfunctiondata = pd.read_csv(BASE / "BirdFuncDat.txt", sep="\t" ,  encoding="latin1")  
avian = pd.read_csv(BASE / "Avian/avian_raw.txt", sep="\t", encoding="latin1", on_bad_lines='warn')

In [3]:
avian

      Family  Species_number              Species_name          English_name   Subspecies    M_mass  M_mass_N    F_mass  F_mass_N  unsexed_mass  unsexed_mass_N  M_wing  M_wing_N  F_wing  F_wing_N  Unsexed_wing  Unsexed_wing_N  M_tarsus  M_tarsus_N  F_tarsus  F_tarsus_N  Unsexed_tarsus  Unsexed_tarsus_N  M_bill  M_bill_N  F_bill  F_bill_N  Unsexed_bill  Unsexed_bill_N  M_tail  M_tail_N  F_tail  F_tail_N  Unsexed_tail  Unsexed_tail_N  Clutch_size  Egg_mass  Mating_System  Display  Resource    References  Unnamed: 41  Unnamed: 42  Unnamed: 43
0          1               1          Struthio camelus               Ostrich         -999  115000.0      -999  100000.0      -999        -999.0            -999  -999.0      -999  -999.0      -999         900.0            -999    -999.0      -999.0    -999.0        -999           450.0              -999  -999.0    -999.0  -999.0    -999.0         135.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0      -999.00   1500.00            4.0     -999      -999     1, 23, 31          NaN          NaN          NaN
1          3               7  Dromaius novaehollandiae                   Emu         -999   32700.0      -999   38300.0      -999        -999.0            -999   200.0        10   203.0        10        -999.0            -999     426.0        11.0     441.0          11          -999.0              -999    59.1      11.0    61.9      11.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         8.98    581.20            1.0        1         0            17          NaN          NaN          NaN
2          4               8         Apteryx australis            Brown Kiwi         -999    2208.0        11    2535.0        26        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      69.9        11.0      73.3          15          -999.0              -999    98.2      11.0   129.9      15.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         2.00    443.00            2.0     -999      -999     1, 17, 31          NaN          NaN          NaN
3          4               9            Apteryx owenii   Little Spotted Kiwi         -999    1135.0        51    1351.0        41        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      74.1        56.0      79.7          46          -999.0              -999    72.0      27.0    87.1      17.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         1.00    285.00            2.0     -999      -999        17, 31          NaN          NaN          NaN
4          4              10           Apteryx haastii    Great Spotted Kiwi         -999    2610.0        12    3270.0         7        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      84.9         7.0      88.4          13          -999.0              -999    96.0       7.0   125.8      13.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         1.00    425.00            2.0     -999      -999        17, 31          NaN          NaN          NaN
...      ...             ...                       ...                   ...          ...       ...       ...       ...       ...           ...             ...     ...       ...     ...       ...           ...             ...       ...         ...       ...         ...             ...               ...     ...       ...     ...       ...           ...             ...     ...       ...     ...       ...           ...             ...          ...       ...            ...      ...       ...           ...          ...          ...          ...
3732     146            9695    Euphagus cyanocephalus    Brewer's Blackbird         -999      67.2        19      58.1        15        -999.0            -999   130.0        10   117.5        10        -999.0            -999      32.2        10.0      30.5          10          -999.0              -999    14.5      25.0    13.1      25.0        -999.0            -999   102.8        25    91.4        25        -999.0          -999.0         4.98      4.55            4.0     -999      -999      1, 7, 31          NaN          NaN          NaN
3733     146            9698     Molothrus bonariensis         Shiny Cowbird         -999      40.0        42      34.1        48        -999.0            -999    96.5        42    85.8        60        -999.0            -999      23.3        12.0      21.9           8          -999.0              -999    12.8      16.0    11.7       9.0        -999.0            -999    70.9        16    61.5         9        -999.0          -999.0      -999.00      4.30            2.0     -999      -999      1, 7, 31          NaN          NaN          NaN
3734     146            9699          Molothrus aeneus       Bronzed Cowbird         -999      68.9       144      56.9       220        -999.0            -999   117.2       144   102.5       218        -999.0            -999    -999.0      -999.0    -999.0        -999          -999.0              -999    22.2     141.0    19.7     220.0        -999.0            -999    78.8       146    68.8       216        -999.0          -999.0         1.00      4.15         -999.0     -999      -999         7, 31          NaN          NaN          NaN
3735     146            9700            Molothrus ater  Brown-headed Cowbird  aqrtemisiae      47.5       283      37.6       352        -999.0            -999   105.9       283    94.9       352        -999.0            -999      25.0       283.0      23.3         352          -999.0              -999    17.3     283.0    15.4     352.0        -999.0            -999    72.7        15    65.3         9        -999.0          -999.0         4.30      3.12            2.0     -999      -999  1, 7, 12, 31          NaN          NaN          NaN
3736     146            9702     Dolichonyx oryzivorus              Bobolink         -999      33.9       142      29.2       130        -999.0            -999    97.4       301    87.5       261        -999.0            -999      26.1        38.0      25.2          23          -999.0              -999    14.3      38.0    13.4      23.0        -999.0            -999    68.4        38    60.9        23        -999.0          -999.0         5.10      2.75            4.0     -999      -999      1, 7, 31          NaN          NaN          NaN

[3737 rows x 44 columns]

In [4]:
def match_and_append(unmatched_df, ref_df, ref_col, id_col,
                     avian_col="Species_name"):
    """
    Match Avian species names against a reference name column.

    Parameters
    ----------
    unmatched_df : DataFrame  — species still needing an Avibase ID
    ref_df       : DataFrame  — reference dataset to match against
    ref_col      : str        — species name column in ref_df
    id_col       : str        — Avibase ID column in ref_df
    avian_col    : str        — key name column in unmatched_df

    Returns
    -------
    new_matches  : DataFrame  — matched rows with (avibase_id, latin_name)
    unmatched_df : DataFrame  — species still unmatched after this pass
    """
    # Standardize names by stripping whitespace
    avian_names = unmatched_df[avian_col].dropna().str.strip()
    ref_names   = set(ref_df[ref_col].dropna().str.strip())

    # Identify matches and non-matches
    matched   = avian_names[avian_names.isin(ref_names)]
    unmatched = avian_names[~avian_names.isin(ref_names)]

    total, n_matched, n_unmatched = len(avian_names), len(matched), len(unmatched)

    # Progress reporting
    print(f"  Total       : {total}")
    print(f"  Matched     : {n_matched}  ({n_matched / total * 100:.1f}%)")
    print(f"  Not matched : {n_unmatched}  ({n_unmatched / total * 100:.1f}%)")

    # Construct the result DataFrame
    new_matches = (
        ref_df[ref_df[ref_col].str.strip().isin(matched.values)]
        [[id_col, ref_col]]
        .rename(columns={id_col: "avibase_id", ref_col: "Species_name"})
        .drop_duplicates()
        .reset_index(drop=True)
    )

    # Update unmatched_df for the next iteration
    unmatched_df = unmatched.reset_index(drop=True).to_frame()
    
    return new_matches, unmatched_df

In [5]:
new_matches, unmatched_df = match_and_append(avian, avonet_crosswalk, "species_birdlife", "avibase_id")
avian_crosswalk = new_matches

  Total       : 3737
  Matched     : 2861  (76.6%)
  Not matched : 876  (23.4%)

In [6]:
new_matches, unmatched_df = match_and_append(unmatched_df, avonet_crosswalk, "species_ebird", "avibase_id")
avian_crosswalk = pd.concat([avian_crosswalk, new_matches]).drop_duplicates().reset_index(drop=True)

  Total       : 876
  Matched     : 100  (11.4%)
  Not matched : 776  (88.6%)

In [7]:
new_matches, unmatched_df = match_and_append(unmatched_df, avonet_crosswalk, "species_birdtree", "avibase_id")
avian_crosswalk = pd.concat([avian_crosswalk, new_matches]).drop_duplicates().reset_index(drop=True)

  Total       : 776
  Matched     : 568  (73.2%)
  Not matched : 208  (26.8%)

In [8]:
avian_crosswalk.duplicated().sum()

np.int64(0)

In [9]:
avian_crosswalk["avibase_id"].duplicated().sum()

np.int64(9)

In [10]:
avian_crosswalk["Species_name"].duplicated().sum()

np.int64(149)

In [11]:
avian_crosswalk["avibase_id"].isnull().sum()

np.int64(0)

In [12]:
avian_crosswalk = avian_crosswalk.drop_duplicates(subset="Species_name").reset_index(drop=True)

In [13]:
avian_crosswalk.shape

(3527, 2)

In [14]:
avian = avian[~avian["Species_name"].str.strip().isin(unmatched_df["Species_name"])]
avian = avian.reset_index(drop=True)

print(f"avian species after dropping unmatched : {len(avian)}")

avian species after dropping unmatched : 3529

In [15]:
avian_crosswalk = avian_crosswalk.merge(
    avian[[
        "Species_name",
        "English_name"
    ]],
    left_on="Species_name",
    right_on="Species_name",
    how="left"
)

print(avian_crosswalk.shape)

(3529, 3)

In [16]:
avian_crosswalk["avibase_id"].isnull().sum()

np.int64(0)

In [17]:
avian = (
    avian
    .merge(
        avian_crosswalk[["Species_name", "avibase_id"]],
        left_on="Species_name",
        right_on="Species_name",
        how="left"
    )
)

print(f"Shape            : {birdbase.shape}")
print(f"Missing avibase_id : {birdbase['avibase_id'].isna().sum()}")

Shape            : (11412, 36)
Missing avibase_id : 0

In [18]:
avian

      Family  Species_number              Species_name          English_name   Subspecies    M_mass  M_mass_N    F_mass  F_mass_N  unsexed_mass  unsexed_mass_N  M_wing  M_wing_N  F_wing  F_wing_N  Unsexed_wing  Unsexed_wing_N  M_tarsus  M_tarsus_N  F_tarsus  F_tarsus_N  Unsexed_tarsus  Unsexed_tarsus_N  M_bill  M_bill_N  F_bill  F_bill_N  Unsexed_bill  Unsexed_bill_N  M_tail  M_tail_N  F_tail  F_tail_N  Unsexed_tail  Unsexed_tail_N  Clutch_size  Egg_mass  Mating_System  Display  Resource    References  Unnamed: 41  Unnamed: 42  Unnamed: 43        avibase_id
0          1               1          Struthio camelus               Ostrich         -999  115000.0      -999  100000.0      -999        -999.0            -999  -999.0      -999  -999.0      -999         900.0            -999    -999.0      -999.0    -999.0        -999           450.0              -999  -999.0    -999.0  -999.0    -999.0         135.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0      -999.00   1500.00            4.0     -999      -999     1, 23, 31          NaN          NaN          NaN  AVIBASE-2247CB05
1          3               7  Dromaius novaehollandiae                   Emu         -999   32700.0      -999   38300.0      -999        -999.0            -999   200.0        10   203.0        10        -999.0            -999     426.0        11.0     441.0          11          -999.0              -999    59.1      11.0    61.9      11.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         8.98    581.20            1.0        1         0            17          NaN          NaN          NaN  AVIBASE-FD2456D5
2          4               8         Apteryx australis            Brown Kiwi         -999    2208.0        11    2535.0        26        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      69.9        11.0      73.3          15          -999.0              -999    98.2      11.0   129.9      15.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         2.00    443.00            2.0     -999      -999     1, 17, 31          NaN          NaN          NaN  AVIBASE-6BA55EF0
3          4               9            Apteryx owenii   Little Spotted Kiwi         -999    1135.0        51    1351.0        41        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      74.1        56.0      79.7          46          -999.0              -999    72.0      27.0    87.1      17.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         1.00    285.00            2.0     -999      -999        17, 31          NaN          NaN          NaN  AVIBASE-187706CF
4          4              10           Apteryx haastii    Great Spotted Kiwi         -999    2610.0        12    3270.0         7        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      84.9         7.0      88.4          13          -999.0              -999    96.0       7.0   125.8      13.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         1.00    425.00            2.0     -999      -999        17, 31          NaN          NaN          NaN  AVIBASE-0D8B9E40
...      ...             ...                       ...                   ...          ...       ...       ...       ...       ...           ...             ...     ...       ...     ...       ...           ...             ...       ...         ...       ...         ...             ...               ...     ...       ...     ...       ...           ...             ...     ...       ...     ...       ...           ...             ...          ...       ...            ...      ...       ...           ...          ...          ...          ...               ...
3528     146            9695    Euphagus cyanocephalus    Brewer's Blackbird         -999      67.2        19      58.1        15        -999.0            -999   130.0        10   117.5        10        -999.0            -999      32.2        10.0      30.5          10          -999.0              -999    14.5      25.0    13.1      25.0        -999.0            -999   102.8        25    91.4        25        -999.0          -999.0         4.98      4.55            4.0     -999      -999      1, 7, 31          NaN          NaN          NaN  AVIBASE-EA5E858A
3529     146            9698     Molothrus bonariensis         Shiny Cowbird         -999      40.0        42      34.1        48        -999.0            -999    96.5        42    85.8        60        -999.0            -999      23.3        12.0      21.9           8          -999.0              -999    12.8      16.0    11.7       9.0        -999.0            -999    70.9        16    61.5         9        -999.0          -999.0      -999.00      4.30            2.0     -999      -999      1, 7, 31          NaN          NaN          NaN  AVIBASE-AA779804
3530     146            9699          Molothrus aeneus       Bronzed Cowbird         -999      68.9       144      56.9       220        -999.0            -999   117.2       144   102.5       218        -999.0            -999    -999.0      -999.0    -999.0        -999          -999.0              -999    22.2     141.0    19.7     220.0        -999.0            -999    78.8       146    68.8       216        -999.0          -999.0         1.00      4.15         -999.0     -999      -999         7, 31          NaN          NaN          NaN  AVIBASE-EAEEA093
3531     146            9700            Molothrus ater  Brown-headed Cowbird  aqrtemisiae      47.5       283      37.6       352        -999.0            -999   105.9       283    94.9       352        -999.0            -999      25.0       283.0      23.3         352          -999.0              -999    17.3     283.0    15.4     352.0        -999.0            -999    72.7        15    65.3         9        -999.0          -999.0         4.30      3.12            2.0     -999      -999  1, 7, 12, 31          NaN          NaN          NaN  AVIBASE-1E1AB415
3532     146            9702     Dolichonyx oryzivorus              Bobolink         -999      33.9       142      29.2       130        -999.0            -999    97.4       301    87.5       261        -999.0            -999      26.1        38.0      25.2          23          -999.0              -999    14.3      38.0    13.4      23.0        -999.0            -999    68.4        38    60.9        23        -999.0          -999.0         5.10      2.75            4.0     -999      -999      1, 7, 31          NaN          NaN          NaN  AVIBASE-F845062F

[3533 rows x 45 columns]

In [19]:
avian.columns

Index(['Family', 'Species_number', 'Species_name', 'English_name', 'Subspecies', 'M_mass', 'M_mass_N', 'F_mass', 'F_mass_N', 'unsexed_mass', 'unsexed_mass_N', 'M_wing', 'M_wing_N', 'F_wing', 'F_wing_N', 'Unsexed_wing', 'Unsexed_wing_N', 'M_tarsus', 'M_tarsus_N', 'F_tarsus', 'F_tarsus_N', 'Unsexed_tarsus', 'Unsexed_tarsus_N', 'M_bill', 'M_bill_N', 'F_bill', 'F_bill_N', 'Unsexed_bill', 'Unsexed_bill_N', 'M_tail', 'M_tail_N', 'F_tail', 'F_tail_N', 'Unsexed_tail', 'Unsexed_tail_N', 'Clutch_size', 'Egg_mass', 'Mating_System', 'Display', 'Resource', 'References', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'avibase_id'], dtype='object')

In [20]:
avian.drop(columns=['Family', 'Species_number', 'Species_name', 'English_name', 
                    'Subspecies', 'Display',
                    'Resource', 'References',
                    'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43'],inplace=True)

In [21]:
avian.shape

(3533, 34)

In [22]:
avian

        M_mass  M_mass_N    F_mass  F_mass_N  unsexed_mass  unsexed_mass_N  M_wing  M_wing_N  F_wing  F_wing_N  Unsexed_wing  Unsexed_wing_N  M_tarsus  M_tarsus_N  F_tarsus  F_tarsus_N  Unsexed_tarsus  Unsexed_tarsus_N  M_bill  M_bill_N  F_bill  F_bill_N  Unsexed_bill  Unsexed_bill_N  M_tail  M_tail_N  F_tail  F_tail_N  Unsexed_tail  Unsexed_tail_N  Clutch_size  Egg_mass  Mating_System        avibase_id
0     115000.0      -999  100000.0      -999        -999.0            -999  -999.0      -999  -999.0      -999         900.0            -999    -999.0      -999.0    -999.0        -999           450.0              -999  -999.0    -999.0  -999.0    -999.0         135.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0      -999.00   1500.00            4.0  AVIBASE-2247CB05
1      32700.0      -999   38300.0      -999        -999.0            -999   200.0        10   203.0        10        -999.0            -999     426.0        11.0     441.0          11          -999.0              -999    59.1      11.0    61.9      11.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         8.98    581.20            1.0  AVIBASE-FD2456D5
2       2208.0        11    2535.0        26        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      69.9        11.0      73.3          15          -999.0              -999    98.2      11.0   129.9      15.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         2.00    443.00            2.0  AVIBASE-6BA55EF0
3       1135.0        51    1351.0        41        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      74.1        56.0      79.7          46          -999.0              -999    72.0      27.0    87.1      17.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         1.00    285.00            2.0  AVIBASE-187706CF
4       2610.0        12    3270.0         7        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      84.9         7.0      88.4          13          -999.0              -999    96.0       7.0   125.8      13.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         1.00    425.00            2.0  AVIBASE-0D8B9E40
...        ...       ...       ...       ...           ...             ...     ...       ...     ...       ...           ...             ...       ...         ...       ...         ...             ...               ...     ...       ...     ...       ...           ...             ...     ...       ...     ...       ...           ...             ...          ...       ...            ...               ...
3528      67.2        19      58.1        15        -999.0            -999   130.0        10   117.5        10        -999.0            -999      32.2        10.0      30.5          10          -999.0              -999    14.5      25.0    13.1      25.0        -999.0            -999   102.8        25    91.4        25        -999.0          -999.0         4.98      4.55            4.0  AVIBASE-EA5E858A
3529      40.0        42      34.1        48        -999.0            -999    96.5        42    85.8        60        -999.0            -999      23.3        12.0      21.9           8          -999.0              -999    12.8      16.0    11.7       9.0        -999.0            -999    70.9        16    61.5         9        -999.0          -999.0      -999.00      4.30            2.0  AVIBASE-AA779804
3530      68.9       144      56.9       220        -999.0            -999   117.2       144   102.5       218        -999.0            -999    -999.0      -999.0    -999.0        -999          -999.0              -999    22.2     141.0    19.7     220.0        -999.0            -999    78.8       146    68.8       216        -999.0          -999.0         1.00      4.15         -999.0  AVIBASE-EAEEA093
3531      47.5       283      37.6       352        -999.0            -999   105.9       283    94.9       352        -999.0            -999      25.0       283.0      23.3         352          -999.0              -999    17.3     283.0    15.4     352.0        -999.0            -999    72.7        15    65.3         9        -999.0          -999.0         4.30      3.12            2.0  AVIBASE-1E1AB415
3532      33.9       142      29.2       130        -999.0            -999    97.4       301    87.5       261        -999.0            -999      26.1        38.0      25.2          23          -999.0              -999    14.3      38.0    13.4      23.0        -999.0            -999    68.4        38    60.9        23        -999.0          -999.0         5.10      2.75            4.0  AVIBASE-F845062F

[3533 rows x 34 columns]

In [23]:
avian.columns

Index(['M_mass', 'M_mass_N', 'F_mass', 'F_mass_N', 'unsexed_mass', 'unsexed_mass_N', 'M_wing', 'M_wing_N', 'F_wing', 'F_wing_N', 'Unsexed_wing', 'Unsexed_wing_N', 'M_tarsus', 'M_tarsus_N', 'F_tarsus', 'F_tarsus_N', 'Unsexed_tarsus', 'Unsexed_tarsus_N', 'M_bill', 'M_bill_N', 'F_bill', 'F_bill_N', 'Unsexed_bill', 'Unsexed_bill_N', 'M_tail', 'M_tail_N', 'F_tail', 'F_tail_N', 'Unsexed_tail', 'Unsexed_tail_N', 'Clutch_size', 'Egg_mass', 'Mating_System', 'avibase_id'], dtype='object')

In [24]:
avian = avian[[ 'avibase_id',
    'M_mass', 'M_mass_N', 'F_mass', 'F_mass_N', 'unsexed_mass',
    'unsexed_mass_N', 'M_wing', 'M_wing_N', 'F_wing', 'F_wing_N', 'Unsexed_wing', 'Unsexed_wing_N',
    'M_tarsus', 'M_tarsus_N', 'F_tarsus', 'F_tarsus_N', 'Unsexed_tarsus', 'Unsexed_tarsus_N', 'M_bill', 
    'M_bill_N', 'F_bill', 'F_bill_N', 'Unsexed_bill', 'Unsexed_bill_N', 'M_tail', 'M_tail_N',
    'F_tail', 'F_tail_N', 'Unsexed_tail', 'Unsexed_tail_N', 'Clutch_size', 'Egg_mass', 'Mating_System'
]]

print(f"Selected features : {avian.shape[1]}  |  Rows : {avian.shape[0]}")

Selected features : 34  |  Rows : 3533

In [25]:
avian

            avibase_id    M_mass  M_mass_N    F_mass  F_mass_N  unsexed_mass  unsexed_mass_N  M_wing  M_wing_N  F_wing  F_wing_N  Unsexed_wing  Unsexed_wing_N  M_tarsus  M_tarsus_N  F_tarsus  F_tarsus_N  Unsexed_tarsus  Unsexed_tarsus_N  M_bill  M_bill_N  F_bill  F_bill_N  Unsexed_bill  Unsexed_bill_N  M_tail  M_tail_N  F_tail  F_tail_N  Unsexed_tail  Unsexed_tail_N  Clutch_size  Egg_mass  Mating_System
0     AVIBASE-2247CB05  115000.0      -999  100000.0      -999        -999.0            -999  -999.0      -999  -999.0      -999         900.0            -999    -999.0      -999.0    -999.0        -999           450.0              -999  -999.0    -999.0  -999.0    -999.0         135.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0      -999.00   1500.00            4.0
1     AVIBASE-FD2456D5   32700.0      -999   38300.0      -999        -999.0            -999   200.0        10   203.0        10        -999.0            -999     426.0        11.0     441.0          11          -999.0              -999    59.1      11.0    61.9      11.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         8.98    581.20            1.0
2     AVIBASE-6BA55EF0    2208.0        11    2535.0        26        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      69.9        11.0      73.3          15          -999.0              -999    98.2      11.0   129.9      15.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         2.00    443.00            2.0
3     AVIBASE-187706CF    1135.0        51    1351.0        41        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      74.1        56.0      79.7          46          -999.0              -999    72.0      27.0    87.1      17.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         1.00    285.00            2.0
4     AVIBASE-0D8B9E40    2610.0        12    3270.0         7        -999.0            -999  -999.0      -999  -999.0      -999        -999.0            -999      84.9         7.0      88.4          13          -999.0              -999    96.0       7.0   125.8      13.0        -999.0            -999  -999.0      -999  -999.0      -999        -999.0          -999.0         1.00    425.00            2.0
...                ...       ...       ...       ...       ...           ...             ...     ...       ...     ...       ...           ...             ...       ...         ...       ...         ...             ...               ...     ...       ...     ...       ...           ...             ...     ...       ...     ...       ...           ...             ...          ...       ...            ...
3528  AVIBASE-EA5E858A      67.2        19      58.1        15        -999.0            -999   130.0        10   117.5        10        -999.0            -999      32.2        10.0      30.5          10          -999.0              -999    14.5      25.0    13.1      25.0        -999.0            -999   102.8        25    91.4        25        -999.0          -999.0         4.98      4.55            4.0
3529  AVIBASE-AA779804      40.0        42      34.1        48        -999.0            -999    96.5        42    85.8        60        -999.0            -999      23.3        12.0      21.9           8          -999.0              -999    12.8      16.0    11.7       9.0        -999.0            -999    70.9        16    61.5         9        -999.0          -999.0      -999.00      4.30            2.0
3530  AVIBASE-EAEEA093      68.9       144      56.9       220        -999.0            -999   117.2       144   102.5       218        -999.0            -999    -999.0      -999.0    -999.0        -999          -999.0              -999    22.2     141.0    19.7     220.0        -999.0            -999    78.8       146    68.8       216        -999.0          -999.0         1.00      4.15         -999.0
3531  AVIBASE-1E1AB415      47.5       283      37.6       352        -999.0            -999   105.9       283    94.9       352        -999.0            -999      25.0       283.0      23.3         352          -999.0              -999    17.3     283.0    15.4     352.0        -999.0            -999    72.7        15    65.3         9        -999.0          -999.0         4.30      3.12            2.0
3532  AVIBASE-F845062F      33.9       142      29.2       130        -999.0            -999    97.4       301    87.5       261        -999.0            -999      26.1        38.0      25.2          23          -999.0              -999    14.3      38.0    13.4      23.0        -999.0            -999    68.4        38    60.9        23        -999.0          -999.0         5.10      2.75            4.0

[3533 rows x 34 columns]

In [26]:
placeholders = [-999, "-999", "missing", "Missing", "MISSING", "etc", "n/a", "N/A", ""]

avian = avian.replace(placeholders, np.nan)

In [27]:
avian

            avibase_id    M_mass  M_mass_N    F_mass  F_mass_N  unsexed_mass  unsexed_mass_N  M_wing  M_wing_N  F_wing  F_wing_N  Unsexed_wing  Unsexed_wing_N  M_tarsus  M_tarsus_N  F_tarsus  F_tarsus_N  Unsexed_tarsus  Unsexed_tarsus_N  M_bill  M_bill_N  F_bill  F_bill_N  Unsexed_bill  Unsexed_bill_N  M_tail  M_tail_N  F_tail  F_tail_N  Unsexed_tail  Unsexed_tail_N  Clutch_size  Egg_mass  Mating_System
0     AVIBASE-2247CB05  115000.0       NaN  100000.0       NaN           NaN             NaN     NaN       NaN     NaN       NaN         900.0             NaN       NaN         NaN       NaN         NaN           450.0               NaN     NaN       NaN     NaN       NaN         135.0             NaN     NaN       NaN     NaN       NaN           NaN             NaN          NaN   1500.00            4.0
1     AVIBASE-FD2456D5   32700.0       NaN   38300.0       NaN           NaN             NaN   200.0      10.0   203.0      10.0           NaN             NaN     426.0        11.0     441.0        11.0             NaN               NaN    59.1      11.0    61.9      11.0           NaN             NaN     NaN       NaN     NaN       NaN           NaN             NaN         8.98    581.20            1.0
2     AVIBASE-6BA55EF0    2208.0      11.0    2535.0      26.0           NaN             NaN     NaN       NaN     NaN       NaN           NaN             NaN      69.9        11.0      73.3        15.0             NaN               NaN    98.2      11.0   129.9      15.0           NaN             NaN     NaN       NaN     NaN       NaN           NaN             NaN         2.00    443.00            2.0
3     AVIBASE-187706CF    1135.0      51.0    1351.0      41.0           NaN             NaN     NaN       NaN     NaN       NaN           NaN             NaN      74.1        56.0      79.7        46.0             NaN               NaN    72.0      27.0    87.1      17.0           NaN             NaN     NaN       NaN     NaN       NaN           NaN             NaN         1.00    285.00            2.0
4     AVIBASE-0D8B9E40    2610.0      12.0    3270.0       7.0           NaN             NaN     NaN       NaN     NaN       NaN           NaN             NaN      84.9         7.0      88.4        13.0             NaN               NaN    96.0       7.0   125.8      13.0           NaN             NaN     NaN       NaN     NaN       NaN           NaN             NaN         1.00    425.00            2.0
...                ...       ...       ...       ...       ...           ...             ...     ...       ...     ...       ...           ...             ...       ...         ...       ...         ...             ...               ...     ...       ...     ...       ...           ...             ...     ...       ...     ...       ...           ...             ...          ...       ...            ...
3528  AVIBASE-EA5E858A      67.2      19.0      58.1      15.0           NaN             NaN   130.0      10.0   117.5      10.0           NaN             NaN      32.2        10.0      30.5        10.0             NaN               NaN    14.5      25.0    13.1      25.0           NaN             NaN   102.8      25.0    91.4      25.0           NaN             NaN         4.98      4.55            4.0
3529  AVIBASE-AA779804      40.0      42.0      34.1      48.0           NaN             NaN    96.5      42.0    85.8      60.0           NaN             NaN      23.3        12.0      21.9         8.0             NaN               NaN    12.8      16.0    11.7       9.0           NaN             NaN    70.9      16.0    61.5       9.0           NaN             NaN          NaN      4.30            2.0
3530  AVIBASE-EAEEA093      68.9     144.0      56.9     220.0           NaN             NaN   117.2     144.0   102.5     218.0           NaN             NaN       NaN         NaN       NaN         NaN             NaN               NaN    22.2     141.0    19.7     220.0           NaN             NaN    78.8     146.0    68.8     216.0           NaN             NaN         1.00      4.15            NaN
3531  AVIBASE-1E1AB415      47.5     283.0      37.6     352.0           NaN             NaN   105.9     283.0    94.9     352.0           NaN             NaN      25.0       283.0      23.3       352.0             NaN               NaN    17.3     283.0    15.4     352.0           NaN             NaN    72.7      15.0    65.3       9.0           NaN             NaN         4.30      3.12            2.0
3532  AVIBASE-F845062F      33.9     142.0      29.2     130.0           NaN             NaN    97.4     301.0    87.5     261.0           NaN             NaN      26.1        38.0      25.2        23.0             NaN               NaN    14.3      38.0    13.4      23.0           NaN             NaN    68.4      38.0    60.9      23.0           NaN             NaN         5.10      2.75            4.0

[3533 rows x 34 columns]

In [28]:
rename_dict = {
    'avibase_id': 'avibase_id',
    # Mass
    'M_mass': 'male_mass', 'M_mass_N': 'male_mass_sample_size',
    'F_mass': 'female_mass', 'F_mass_N': 'female_mass_sample_size',
    'unsexed_mass': 'unsexed_mass', 'unsexed_mass_N': 'unsexed_mass_sample_size',
    
    # Wing
    'M_wing': 'male_wing_length', 'M_wing_N': 'male_wing_sample_size',
    'F_wing': 'female_wing_length', 'F_wing_N': 'female_wing_sample_size',
    'Unsexed_wing': 'unsexed_wing_length', 'Unsexed_wing_N': 'unsexed_wing_sample_size',
    
    # Tarsus
    'M_tarsus': 'male_tarsus_length', 'M_tarsus_N': 'male_tarsus_sample_size',
    'F_tarsus': 'female_tarsus_length', 'F_tarsus_N': 'female_tarsus_sample_size',
    'Unsexed_tarsus': 'unsexed_tarsus_length', 'Unsexed_tarsus_N': 'unsexed_tarsus_sample_size',
    
    # Bill
    'M_bill': 'male_bill_length', 'M_bill_N': 'male_bill_sample_size',
    'F_bill': 'female_bill_length', 'F_bill_N': 'female_bill_sample_size',
    'Unsexed_bill': 'unsexed_bill_length', 'Unsexed_bill_N': 'unsexed_bill_sample_size',
    
    # Tail
    'M_tail': 'male_tail_length', 'M_tail_N': 'male_tail_sample_size',
    'F_tail': 'female_tail_length', 'F_tail_N': 'female_tail_sample_size',
    'Unsexed_tail': 'unsexed_tail_length', 'Unsexed_tail_N': 'unsexed_tail_sample_size',
    
    # Life History & Metadata
    'Clutch_size': 'clutch_size',
    'Egg_mass': 'egg_mass',
    'Mating_System': 'mating_system',
    
}

# Apply the rename
avian = avian.rename(columns=rename_dict)

In [29]:
avian.head()

         avibase_id  male_mass  male_mass_sample_size  female_mass  female_mass_sample_size  unsexed_mass  unsexed_mass_sample_size  male_wing_length  male_wing_sample_size  female_wing_length  female_wing_sample_size  unsexed_wing_length  unsexed_wing_sample_size  male_tarsus_length  male_tarsus_sample_size  female_tarsus_length  female_tarsus_sample_size  unsexed_tarsus_length  unsexed_tarsus_sample_size  male_bill_length  male_bill_sample_size  female_bill_length  female_bill_sample_size  unsexed_bill_length  unsexed_bill_sample_size  male_tail_length  male_tail_sample_size  female_tail_length  female_tail_sample_size  unsexed_tail_length  unsexed_tail_sample_size  clutch_size  egg_mass  mating_system
0  AVIBASE-2247CB05   115000.0                    NaN     100000.0                      NaN           NaN                       NaN               NaN                    NaN                 NaN                      NaN                900.0                       NaN                 NaN                      NaN                   NaN                        NaN                  450.0                         NaN               NaN                    NaN                 NaN                      NaN                135.0                       NaN               NaN                    NaN                 NaN                      NaN                  NaN                       NaN          NaN    1500.0            4.0
1  AVIBASE-FD2456D5    32700.0                    NaN      38300.0                      NaN           NaN                       NaN             200.0                   10.0               203.0                     10.0                  NaN                       NaN               426.0                     11.0                 441.0                       11.0                    NaN                         NaN              59.1                   11.0                61.9                     11.0                  NaN                       NaN               NaN                    NaN                 NaN                      NaN                  NaN                       NaN         8.98     581.2            1.0
2  AVIBASE-6BA55EF0     2208.0                   11.0       2535.0                     26.0           NaN                       NaN               NaN                    NaN                 NaN                      NaN                  NaN                       NaN                69.9                     11.0                  73.3                       15.0                    NaN                         NaN              98.2                   11.0               129.9                     15.0                  NaN                       NaN               NaN                    NaN                 NaN                      NaN                  NaN                       NaN         2.00     443.0            2.0
3  AVIBASE-187706CF     1135.0                   51.0       1351.0                     41.0           NaN                       NaN               NaN                    NaN                 NaN                      NaN                  NaN                       NaN                74.1                     56.0                  79.7                       46.0                    NaN                         NaN              72.0                   27.0                87.1                     17.0                  NaN                       NaN               NaN                    NaN                 NaN                      NaN                  NaN                       NaN         1.00     285.0            2.0
4  AVIBASE-0D8B9E40     2610.0                   12.0       3270.0                      7.0           NaN                       NaN               NaN                    NaN                 NaN                      NaN                  NaN                       NaN                84.9                      7.0                  88.4                       13.0                    NaN                         NaN              96.0                    7.0               125.8                     13.0                  NaN                       NaN               NaN                    NaN                 NaN                      NaN                  NaN                       NaN         1.00     425.0            2.0

In [30]:
avian.isnull().sum().sort_values(ascending=False)

unsexed_wing_sample_size      3457
unsexed_tail_sample_size      3436
unsexed_wing_length           3427
unsexed_bill_sample_size      3423
unsexed_tarsus_sample_size    3416
unsexed_tail_length           3401
unsexed_bill_length           3395
unsexed_tarsus_length         3373
unsexed_mass_sample_size      3179
unsexed_mass                  2636
mating_system                 2400
female_mass_sample_size       1680
male_mass_sample_size         1582
female_tarsus_sample_size     1516
male_tarsus_sample_size       1477
female_bill_sample_size       1407
male_bill_sample_size         1367
female_tail_sample_size       1360
male_tail_sample_size         1322
female_tail_length            1282
clutch_size                   1265
male_tail_length              1246
female_wing_sample_size       1245
male_wing_sample_size         1215
female_tarsus_length          1168
male_tarsus_length            1131
egg_mass                      1104
female_bill_length            1062
male_bill_length              1021
female_mass                   1010
male_mass                      898
female_wing_length             726
male_wing_length               701
avibase_id                       0
dtype: int64

In [31]:
avonet.head()

         avibase_id beak_culmen_avg beak_culmen_avg_m beak_culmen_avg_f beak_nares_avg beak_nares_avg_m beak_nares_avg_f beak_width_avg beak_width_avg_m beak_width_avg_f beak_depth_avg beak_depth_avg_m beak_depth_avg_f tarsus_avg tarsus_avg_m tarsus_avg_f wing_len_avg wing_len_avg_m wing_len_avg_f kipps_avg kipps_avg_m kipps_avg_f secondary_avg secondary_avg_m secondary_avg_f   hwi_avg hwi_avg_m hwi_avg_f   tail_avg tail_avg_m tail_avg_f total_individuals female_count male_count    mass_avg mass_source inference    habitat habitat_density migration trophic_level trophic_niche    lifestyle    lat_min   lat_max lat_centroid lon_centroid     range_size
0  AVIBASE-B3F5E5E2        13.00000          12.13333          14.30000        9.50000          9.00000         10.00000        1.18000          1.23333          1.10000        1.68000          1.63333          1.75000    6.34000      5.53333      7.55000     47.00000       48.33333       45.00000  30.50000    30.50000    30.50000      15.50000        16.50000        14.50000  66.35000  64.90000  67.80000   29.40000   30.00000   28.50000           5.00000      2.00000    3.00000     2.70000     Dunning        NO     Forest         2.00000   1.00000     Herbivore   Nectarivore       Aerial   12.78000  19.77000     15.29000    -89.79000   144610.40000
1  AVIBASE-684016CB         8.98000           9.06667           8.85000        4.90000          4.90000          4.90000        2.74000          2.66667          2.85000        2.34000          2.36667          2.30000   15.28000     15.43333     15.05000     43.40000       44.16667       42.25000   5.70000     5.80000     5.60000      37.30000        37.95000        36.65000  13.27500  13.25000  13.30000   38.70000   38.83333   38.50000           5.00000      2.00000    3.00000     4.80000     Dunning        NO     Forest         1.00000   1.00000     Carnivore   Invertivore  Insessorial   14.97000  31.56000     24.78000    105.57000  1704650.60000
2  AVIBASE-0FD03AFF         8.95000           8.80000           9.00000        4.67500          4.50000          4.73333        2.60000          2.70000          2.56667        2.32500          2.50000          2.26667   16.52500     16.80000     16.43333     47.12500       48.00000       46.83333   7.60000     8.40000     7.33333      39.52500        39.60000        39.50000  16.12500  17.50000  15.66667   47.50000   48.00000   47.33333           4.00000      3.00000    1.00000     4.70000     Dunning        NO     Forest         1.00000   1.00000     Carnivore   Invertivore  Insessorial   20.19000  31.12000     26.70000     95.58000   909217.05000
3  AVIBASE-A8F5D21F        12.32000          12.26667          12.40000        7.37500          7.35000          7.40000        3.12000          3.10000          3.15000        2.84000          2.96667          2.65000   16.58000     16.76667     16.30000     51.20000       52.33333       49.50000   6.47500     6.70000     6.25000      44.52500        45.80000        43.25000  12.70000  12.75000  12.65000   42.40000   44.33333   39.50000           5.00000      2.00000    3.00000     6.50000     Dunning        NO  Shrubland         1.00000   1.00000     Carnivore   Invertivore  Insessorial   -8.11000  28.81000      9.89000    105.20000  2493437.47000
4  AVIBASE-50A42775        37.11667          38.88333          35.35000       16.62500         17.20000         16.05000        9.26250          9.27500          9.25000       10.25000         11.30000          9.20000   65.81667     68.50000     63.13333    337.18182      343.40000      332.00000  52.50000    52.50000    52.50000     283.10000       291.50000       277.50000  15.66000  15.30000  15.90000  290.37500  300.33333  280.41667          12.00000      6.00000    6.00000  1405.10000     Dunning        NO     Forest         1.00000   1.00000     Herbivore     Frugivore  Insessorial  -13.43000  11.15000     -2.79000    -75.23000   139314.36000

In [32]:
col =[
    'avibase_id',
  
    'male_mass',  'male_mass_sample_size',
    'female_mass',  'female_mass_sample_size',
    
   'male_wing_length',  'male_wing_sample_size',
    'female_wing_length',  'female_wing_sample_size',
   
     'male_tarsus_length','male_tarsus_sample_size',
   'female_tarsus_length',  'female_tarsus_sample_size',
   
    'male_bill_length', 'male_bill_sample_size',
     'female_bill_length',  'female_bill_sample_size',
    
     'male_tail_length',  'male_tail_sample_size',
    'female_tail_length',  'female_tail_sample_size',
    
     'clutch_size',
     "egg_mass"
]

In [33]:
avian = avian[col]

In [34]:
avian

            avibase_id  male_mass  male_mass_sample_size  female_mass  female_mass_sample_size  male_wing_length  male_wing_sample_size  female_wing_length  female_wing_sample_size  male_tarsus_length  male_tarsus_sample_size  female_tarsus_length  female_tarsus_sample_size  male_bill_length  male_bill_sample_size  female_bill_length  female_bill_sample_size  male_tail_length  male_tail_sample_size  female_tail_length  female_tail_sample_size  clutch_size  egg_mass
0     AVIBASE-2247CB05   115000.0                    NaN     100000.0                      NaN               NaN                    NaN                 NaN                      NaN                 NaN                      NaN                   NaN                        NaN               NaN                    NaN                 NaN                      NaN               NaN                    NaN                 NaN                      NaN          NaN   1500.00
1     AVIBASE-FD2456D5    32700.0                    NaN      38300.0                      NaN             200.0                   10.0               203.0                     10.0               426.0                     11.0                 441.0                       11.0              59.1                   11.0                61.9                     11.0               NaN                    NaN                 NaN                      NaN         8.98    581.20
2     AVIBASE-6BA55EF0     2208.0                   11.0       2535.0                     26.0               NaN                    NaN                 NaN                      NaN                69.9                     11.0                  73.3                       15.0              98.2                   11.0               129.9                     15.0               NaN                    NaN                 NaN                      NaN         2.00    443.00
3     AVIBASE-187706CF     1135.0                   51.0       1351.0                     41.0               NaN                    NaN                 NaN                      NaN                74.1                     56.0                  79.7                       46.0              72.0                   27.0                87.1                     17.0               NaN                    NaN                 NaN                      NaN         1.00    285.00
4     AVIBASE-0D8B9E40     2610.0                   12.0       3270.0                      7.0               NaN                    NaN                 NaN                      NaN                84.9                      7.0                  88.4                       13.0              96.0                    7.0               125.8                     13.0               NaN                    NaN                 NaN                      NaN         1.00    425.00
...                ...        ...                    ...          ...                      ...               ...                    ...                 ...                      ...                 ...                      ...                   ...                        ...               ...                    ...                 ...                      ...               ...                    ...                 ...                      ...          ...       ...
3528  AVIBASE-EA5E858A       67.2                   19.0         58.1                     15.0             130.0                   10.0               117.5                     10.0                32.2                     10.0                  30.5                       10.0              14.5                   25.0                13.1                     25.0             102.8                   25.0                91.4                     25.0         4.98      4.55
3529  AVIBASE-AA779804       40.0                   42.0         34.1                     48.0              96.5                   42.0                85.8                     60.0                23.3                     12.0                  21.9                        8.0              12.8                   16.0                11.7                      9.0              70.9                   16.0                61.5                      9.0          NaN      4.30
3530  AVIBASE-EAEEA093       68.9                  144.0         56.9                    220.0             117.2                  144.0               102.5                    218.0                 NaN                      NaN                   NaN                        NaN              22.2                  141.0                19.7                    220.0              78.8                  146.0                68.8                    216.0         1.00      4.15
3531  AVIBASE-1E1AB415       47.5                  283.0         37.6                    352.0             105.9                  283.0                94.9                    352.0                25.0                    283.0                  23.3                      352.0              17.3                  283.0                15.4                    352.0              72.7                   15.0                65.3                      9.0         4.30      3.12
3532  AVIBASE-F845062F       33.9                  142.0         29.2                    130.0              97.4                  301.0                87.5                    261.0                26.1                     38.0                  25.2                       23.0              14.3                   38.0                13.4                     23.0              68.4                   38.0                60.9                     23.0         5.10      2.75

[3533 rows x 23 columns]

In [35]:
avian.to_csv(
    '../data/raw/Avian/avian_uncleaned_final_dataset.csv',
    index=False,                 
    float_format='%.5f' 
)

In [36]:
avian_crosswalk.to_csv(
    '../data/raw/Avian/avian_crosswalk.csv',
    index=False,                 
)